### ISSUE TITLE
[iOS]pod error: "cannot find ./ios/build/ezlog.xcframework.zip.ZIP, period."

### ISSUE THREAD

**Issue by shoguncao** [s1rius/ezlog#109]
pod 'EZLog', :git => 'https://github.com/s1rius/ezlog.git'
bug get error:

`Analyzing dependencies
Pre-downloading: `EZLog` from `https://github.com/s1rius/ezlog.git`
[!] Failed to download 'EZLog': [!] /bin/bash -c 
set -e
if [ -d "./ios/framework/" ] && [ "$(find ./ios/framework/ -mindepth 1 -print -quit)" ]; then
  echo "framework folder exists and is not empty， exit"
  exit 0
fi
echo "download framework from internet"
mkdir ./ios/build
curl -L -o ./ios/build/ezlog.xcframework.zip "https://github.com/s1rius/ezlog/releases/download/0.2.0/ezlog_0.2.0_xcframework.zip"
if [ -s "./ios/build/ezlog.xcframework.zip" ]; then
  echo "unzip xcframework"
  unzip -o ./ios/build/ezlog.xcframework.zip -d ./ios/framework
else
  echo "xcframework build from source"
  pushd ios
  sh b_ios.sh
fi

download framework from internet
unzip xcframework
Archive:  ./ios/build/ezlog.xcframework.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     21      0 --:--:-- --:--:-- --:--:--    21
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ./ios/build/ezlog.xcframework.zip or
        ./ios/build/ezlog.xcframework.zip.zip, and cannot find ./ios/build/ezlog.xcframework.zip.ZIP, period.`

**Comment by s1rius** [comment]
Thank you for report this, It should be fixed now.
